#!/usr/bin/env bash

echo "Installing Dotfiles"

SOURCE_DIR="./src"
TARGET_DIR="$HOME"

PACKAGES=("nvim" "tmux" "kitty" "wezterm" "zsh")

for package in "${PACKAGES[@]}"
do
	echo "Installing $package"
	stow -t $TARGET_DIR $package
done

